name: Manual build
on: [workflow_dispatch]
jobs:
    build:
       runs-on: ubuntu-latest
       steps:
          - name: Clone repository
            uses: actions/checkout@v2
          - name: Print env
            run: printenv
          - name: Build runtime
            run: docker run --network=host -i --rm -v $(pwd):/mnt/build -t $(docker build -q . -f ./.github/docker/Dockerfile.build) ./.github/scripts/build_runtime.sh
